name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-windows:
    runs-on: windows-latest



    steps:
      - name: Lay source code
        uses: actions/checkout@v4

      - name: Cai Node.js LTS 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Kiem tra file app
        shell: cmd
        run: |
          dir
          if not exist package.json exit /b 1
          if not exist main.js exit /b 1
          if not exist preload.js exit /b 1

      - name: Cai thu vien
        shell: cmd
        run: |
          npm config set ignore-scripts false
          npm config set fund false
          npm config set audit false
          npm install --foreground-scripts

      - name: Build file cai dat EXE
        shell: cmd
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
          npm_config_electron_mirror: https://npmmirror.com/mirrors/electron/
        run: |
          npm run build

      - name: Luu file cai dat de tai ve
        uses: actions/upload-artifact@v4
        with:
          name: AppKhoNhieuLoc-Windows-EXE
          path: |
            AppKhoNhieuLoc_BUILD_READY/dist/*.exe
            AppKhoNhieuLoc_BUILD_READY/dist/*.blockmap
          if-no-files-found: error
